version: '3.8'
services:
  backend:
    build:
      context: ./blog-backend
    ports:
      - "5000:5000"
    env_file:
      - ./blog-backend/.env
  frontend:
    build:
      context: ./blog-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./blog-frontend/.env
