services:
  backend:
    build:
      context: ./blog-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:qwer5555@db:5432/blog
    depends_on:
      - db

  frontend:
    build:
      context: ./blog-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer5555
      POSTGRES_DB: auth_app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
